# Second stage: add LIO-SAM
FROM ros2-dev-gpu-s1 AS ros2-dev-gpu-liosam

RUN apt-get update && apt-get install -y curl nlohmann-json3-dev
RUN curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | apt-key add -
RUN apt-get update && apt install -y python3-colcon-common-extensions \
    ros-humble-navigation2 \
    ros-humble-robot-localization \
    ros-humble-robot-state-publisher \
    ros-humble-perception-pcl \
    ros-humble-pcl-msgs \
    ros-humble-vision-opencv \
    ros-humble-xacro \
    && rm -rf /var/lib/apt/lists/*
# TODO: consider moving the above to the base image

RUN apt-get update && apt install -y software-properties-common
RUN add-apt-repository -y ppa:borglab/gtsam-release-4.1
RUN apt-get update && apt install -y libgtsam-dev libgtsam-unstable-dev \
    && rm -rf /var/lib/apt/lists/*

SHELL ["/bin/bash", "-c"]

WORKDIR /ros2_ws
RUN source /opt/ros/humble/setup.bash

RUN mkdir -p /ros2_ws/src_lio_sam \
    && cd /ros2_ws/src_lio_sam \
    && git clone --branch ros2 https://github.com/TixiaoShan/LIO-SAM.git \
    && cd .. \
    && source /opt/ros/humble/setup.bash \
    && colcon build

# RUN echo "source /opt/ros/humble/setup.bash" >> /root/.bashrc \
#     && echo "source /ros2_ws/install/setup.bash" >> /root/.bashrc

ENTRYPOINT ["/ros_entrypoint_nvidia.sh"]

CMD ["bash"]
